---
# This user will run administrative tasks (and also host
# support files if we deem so)
admin_user: chesterbr
admin_user_key: https://github.com/chesterbr.keys
admin_deploy_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH3mHqhrtpzxMYnVlYYLEpK2nqfbsZ3V4ea6QvyxInFu github-actions-deploy"
admin_email: cd@pobox.com

# User that will host and execute the server apps  (non-sudoer, can't log in)
server_user: server

# Ansible needs to use Python 2.7
ansible_python_interpreter: /usr/bin/python2.7

# Basic nginx configuration: disable default site, add chester.me and redirects
nginx_sites:
  - server:
      listen: 80 default_server
      file_name: default
      server_name: _
      return: 444

# Cruzalinhas options
cruzalinhas_checkout_dir: /home/server/cruzalinhas/source
sptrans_gtfs_filename: '/home/server/cruzalinhas/source/public/gtfs-sptrans.zip'

# Toronto Transit for Pebble options
totransit_checkout_dir: /home/server/totransit/source
totransit_app_dir: /home/server/totransit/source/server

# Minitruco (server)
minitruco_checkout_dir: /home/server/minitruco/source
minitruco_log_file: /var/log/supervisor/minitruco.log
minitruco_port: 6912
minitruco_rate_limit_max_per_period_from_same_ip: 20
minitruco_rate_limit_period_in_seconds: 30

# Staticman (comments for chester.me)
staticman_checkout_dir: /home/server/staticman/source
