---

# See: https://github.com/georchestra/ansible/issues/55#issuecomment-588313638
- name: Ensure setfacl is present (so "become_user:" in playbooks works for less privileged ones)
  apt: name=acl state=present

- name: Install unattended upgrades package and dependencies.
  apt: pkg={{ packages }} state=present
  vars:
    packages:
      - unattended-upgrades
      - update-notifier-common
      - mailutils

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades

- name: Configure ufw (firewall) to allow specific ports
  become: yes
  ufw: rule=allow port={{ item }}
  with_items:
    - 22
    - 80
    - 443
  tags:
    - firewall

- name: Enable ufw and load it on startup; reject any connections not on rules
  become: yes
  ufw: state=enabled policy=reject
  tags:
    - firewall

- name: Update SSH configuration to be more secure
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"

- name: Install fail2ban.
  apt: name=fail2ban state=present

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes

# This is the last thing we should do - after that, ssh as root
# won't be accepted. It must use raw because otherwise Ansible
# does one last ssh, fails and fail2ban locks us out.
- name: restart sshd to make new configuration effective
  raw: "systemctl restart sshd"

