---

# See: https://github.com/georchestra/ansible/issues/55#issuecomment-588313638
- name: Ensure setfacl is present (so "become_user:" in playbooks works for less privileged ones)
  apt: name=acl state=present

- name: Install unattended upgrades package and dependencies.
  apt: pkg={{ packages }} state=present
  vars:
    packages:
      - unattended-upgrades
      - update-notifier-common
      - mailutils

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades

- name: Ensure maintenance scripts directory exists
  become: true
  file:
    path: /opt/scripts
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy script that will soft shutdown all services and reboot if a reboot is required
  become: true
  template:
    src: "../templates/reboot_if_required.sh"
    dest: "/opt/scripts/reboot_if_required.sh"
    owner: root
    group: root
    mode: 0755

- name: Do the updates reboot (if required) every day at 5AM UTC (the server expected timezone), so it reboots at 2AM or 3AM in Brazil, and midnight or 1AM in Toronto
  become: true
  cron:
    name: "Run reboot_if_required.sh"
    minute: 0
    hour: 5
    job: "/opt/scripts/reboot_if_required.sh"
    user: root

- name: Configure ufw (firewall) to allow specific ports
  become: yes
  ufw: rule=allow port={{ item }}
  with_items:
    - 22
    - 80
    - 443
  tags:
    - firewall

- name: Enable ufw and load it on startup; reject any connections not on rules
  become: yes
  ufw: state=enabled policy=reject
  tags:
    - firewall

- name: Update SSH configuration to be more secure
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"

- name: Install fail2ban.
  apt: name=fail2ban state=present

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes
