---
- hosts: all
  remote_user: "{{ admin_user }}"

  handlers:
    - name: reload supervisor
      shell: "service supervisor restart; supervisorctl reload"
      become: yes

    - name: restart app
      shell: "supervisorctl restart cruzalinhas"
      become: yes

  roles:
    - role: chesterbr.vault
    - role: chesterbr.nginx
      nginx_sites:
        - server:
            file_name: cruzalinhas.com
            root: "{{ cruzalinhas_checkout_dir }}/public"
            server_name: cruzalinhas.com dev.cruzalinhas.com
            location1: { name: '~ .*', proxy_pass: 'http://cruzalinhas_rails' }
        - server:
            file_name: redirects.cruzalinhas.com
            server_name: www.cruzalinhas.com www.cruzalinhas.com.br cruzalinhas.com.br
            return: 301 $scheme://cruzalinhas.com$request_uri
    - role: chesterbr.ruby
      ruby_user: "{{ admin_user }}"

  tasks:
    - name: Install prereq packages
      apt: name={{ item }} state=installed
      become: yes
      with_items:
        - git
        - libsqlite3-dev
        - xvfb
        - firefox
        - python-pip
        - default-jdk
        - nodejs
        - makepasswd
        - supervisor

    - name: "Auto-start supervisord on boot (temp fix for Ubuntu 16.04 bug: https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1594740)"
      shell: "systemctl enable supervisor; systemctl start supervisor"
      become: yes

    - name: Add cruzalinhas upstream to server config
      become: yes
      lineinfile: dest=/etc/nginx/sites-enabled/cruzalinhas.com insertbefore="BOF" line="upstream cruzalinhas_rails { server 127.0.0.1:3000; }"
      notify:
       - reload nginx

    - name: Ensure code repository is at latest version
      git: repo=git://github.com/chesterbr/cruzalinhas.git
           accept_hostkey=true
           dest={{ cruzalinhas_checkout_dir }}
           version=master
      notify: restart app
      tags:
        - update_app

    - name: Ensure we're always in production rails environment
      lineinfile: dest=~/.profile line="export RAILS_ENV=production" regexp="^export RAILS_ENV"

    - name: Configure a keybase for cookie signing
      lineinfile: dest=~/.profile line="export SECRET_KEY_BASE={{ cruzalinhas_secret_key_base }}" regexp="^export SECRET_KEY_BASE"

    - name: "Install ruby required by the code (e.g.: .ruby_version)"
      shell: bash -lc "cd {{ cruzalinhas_checkout_dir }}; rbenv install"
      register: ruby_install_result
      failed_when: ruby_install_result.rc != 0 and not (ruby_install_result.stderr | search('^rbenv.*versions.*already exists$'))

    - name: Ensure we have all gem dependencies for cruzalinhas
      command: bash -lc "cd {{ cruzalinhas_checkout_dir }}; gem install bundle; bundle install"
      register: bundler
      changed_when: '"Installing" in bundler.stdout'

    - name: Configures cruzalinhas back-end to run under supervisor (from source dir)
      template: src=templates/cruzalinhas.conf.supervisor.j2 dest=/etc/supervisor/conf.d/cruzalinhas.conf
      become: yes
      notify: reload supervisor

    - name: Ensure temp directory exists (needed for first-time data load)
      file: path={{ cruzalinhas_checkout_dir }}/tmp/cache state=directory

    - name: Install Selenium bindings for Python and headless display utility
      pip: name={{ item }}
      become: yes
      with_items:
        - selenium
        - pyvirtualdisplay

    - name: Install sptrans data download script
      template: src=templates/download_sptrans_gtfs.py.j2 dest={{ cruzalinhas_download_sptrans_script }} owner={{ admin_user }}

    - name: Download latest sptrans data
      command: bash -lc "python {{ cruzalinhas_download_sptrans_script }}"
      tags:
        - update_sptrans_data

    - name: Update SPTrans data
      command: bash -lc "cd {{ cruzalinhas_checkout_dir }}; bundle exec rake sptrans:import"
      notify: restart app
      tags:
        - update_sptrans_data

# TODO:
# config crontab with download & update sptrans
