# Initial configuration for the Raspberry Pi that handles my home automation
#
# This playbook just ensures I have my user there, that it is a sudoer and
# that I can ssh with my own key, so I can use it for all other tasks
# in the main playbook (rpi.yml).
#
# Given it will likely be ran when an image was freshly baked, we also use the
# opportunity to bump all packages to latest in distro, configure my chosen
# hostname/timezone/static IP and give it a good reboot, so it's ready to rumble
#
# To provision from zero:
#   - Burn Raspbian (>= Stretch) Lite image to SD with balenaEtecher (or dd)
#   - Before putting the SD card on RPi, mount it and:
#     - Create empty SSH file (touch /Volumes/boot/SSH)
#     - Create wpa_supplicant.conf (vi /Volumes/boot/wpa_supplicant.conf)
#       (model here: https://raspberrypi.stackexchange.com/a/82923/100572)
#   - Unmount, put on RPi and boot it
#   - Wait a bit (it will cycle-boot at least once), figure out the IP it got
#     from the router (either look at screen or router setup), then run:
#     below (password is raspberry):
#        ansible-playbook rpi_provisioning.yml -k
#   - Supply the default "raspberry" password (for the last time in your life)
#
# Hints:
#   - Ensure your router is redirecting ports 80, 443 and 8123 to
#     this RPi's network adaptor (also 22 once it's fully locked down)
#   - mDNS just works: once you reboot, you should be able to
#     access your RPi with <host>.local (e.g.: tv-pi.local on mine)
#     for ssh, etc.
#   - Easy way to make your computer forget about old versions of
#     that ip/hostname:
#       ssh-keygen -R ip.of.your.pi
#       ssh-keygen -R <host>.local
#   - My network went bananas when I tried to access my dynamic DNS name,
#     but adding an entry pointing it to the internal IP of the RPi
#     to /etc/hosts (or better: your router's DNS, if it allwos that)
#     fixes it.

- hosts: raspberrypi_unprovisioned
  remote_user: pi
  become: yes
  become_method: sudo
  vars:
    admin_user: chesterbr
    admin_user_key: https://github.com/chesterbr.keys
    host: tv-pi
    interface: wlan0
    ipaddress: 10.88.111.201
    routers: 10.88.111.254
    dns_servers: 10.88.111.1

  roles:
  - chesterbr.user_setup

  tasks:
  - name: Update all packages to latest within distro, then remove unneeded
    block:
      - apt: update_cache=yes upgrade=dist
      - apt: autoremove=yes

  - name: Configure the hostname
    block:
      - replace:
          dest: "/etc/hosts"
          regexp: "raspberrypi"
          replace: "{{ host }}"
      - hostname:
          name: "{{ host }}"

  - name: Configure timezone
    timezone:
      name: America/Toronto

  - name: Configure static IP
    lineinfile:
      dest:  /etc/dhcpcd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regexp: "^interface eth[0-9]$", line: "interface {{ interface }}" }
      - { regexp: "^static ip_address", line: "static ip_address={{ ipaddress }}" }
      - { regexp: "^static routers", line: "static routers={{ routers }}" }
      - { regexp: "^static domain_name_servers", line: "static domain_name_servers={{ dns_servers }}" }

  - name: Configure the pen drive for backups
    mount:
      path: /media/usb_backup
      src: /dev/sda1
      fstype: vfat
      opts: uid=1001,gid=1001,
      state: mounted

  - name: Reboot
    reboot:
