- name: Run Ansible playbook
  uses: dawidd6/action-ansible-playbook@v2.5.0
  with:
    playbook: cruzalinhas.yml
    key: ${{secrets.SSH_PRIVATE_KEY}}
    # Optional, encrypted vault password
    vault_password: ${{secrets.VAULT_PASSWORD}}
    options: |
      --tags update_at
      --inventory hosts
      --verbose
